name: Waka Readme

on:
  schedule:
    # Runs at 12am IST
    - cron: '30 18 * * 1'
  workflow_dispatch:
jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          COMMIT_BY_ME: True
          COMMIT_USERNAME: khoakomlem
          COMMIT_EMAIL: khoakomlem@gmail.com
          COMMIT_MESSAGE: 📈 Update WakaTime stats
          SHOW_UPDATED_DATE: false
          UPDATED_DATE_FORMAT: "%A, %d/%m/%y at %I:%M %p"
          SHOW_LINES_OF_CODE: false
          SHOW_TOTAL_CODE_TIME: true
          SHOW_PROFILE_VIEWS: false
          SHOW_COMMIT: false
          SHOW_DAYS_OF_WEEK: false
          SHOW_SHORT_INFO: false
          SHOW_LOC_CHART: false
          SHOW_PROJECTS: false
          SHOW_EDITORS: false
          SHOW_OS: false

  snake-generate:
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark
            dist/ocean.gif?color_snake=orange&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9
