name: Waka Readme

on:
  schedule:
    # Runs at 12am IST
    - cron: '30 18 * * *'
  workflow_dispatch:
jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SECTION_NAME: TESTSECTION
          COMMIT_BY_ME: True
          COMMIT_USERNAME: khoakomlem
          COMMIT_EMAIL: khoakomlem@gmail.com
          COMMIT_MESSAGE: 📈 Update WakaTime stats
          SHOW_UPDATED_DATE: true
          UPDATED_DATE_FORMAT: "%A, %d/%m/%y at %I:%M %p"
          SHOW_LINES_OF_CODE: false
          SHOW_TOTAL_CODE_TIME: false
          SHOW_PROFILE_VIEWS: false
          SHOW_COMMIT: false
          SHOW_DAYS_OF_WEEK: false
          SHOW_SHORT_INFO: false
          SHOW_LOC_CHART: false
